/* Copyright 2018 Pedro Cuadra - pjcuadra@gmail.com
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/* WARNING: This file is automatically generated by raml2agl */
#include <service/ServiceRoverLights.h>

ServiceRoverLights::ServiceRoverLights() {
  AFB_NOTICE("[ServiceRoverLights] Constructor ");
}

int ServiceRoverLights::init() {
  AFB_NOTICE("[ServiceRoverLights] Init ");
  return -1;
}


/** Autogenrated doc for parking_signal_on */
int ServiceRoverLights::parking_signal_on() {

  AFB_NOTICE("[ServiceRoverLights] Parking_signal_on");
  AFB_ERROR("Method Parking_signal_on not implemented");

  return -1;
}

/** Autogenrated doc for turn_off_lights */
int ServiceRoverLights::turn_off_lights() {

  AFB_NOTICE("[ServiceRoverLights] Turn_off_lights");
  AFB_ERROR("Method Turn_off_lights not implemented");

  return -1;
}

/** Autogenrated doc for turn_on_lights */
int ServiceRoverLights::turn_on_lights() {

  AFB_NOTICE("[ServiceRoverLights] Turn_on_lights");
  AFB_ERROR("Method Turn_on_lights not implemented");

  return -1;
}

/** Autogenrated doc for turning_left_on */
int ServiceRoverLights::turning_left_on() {

  AFB_NOTICE("[ServiceRoverLights] Turning_left_on");
  AFB_ERROR("Method Turning_left_on not implemented");

  return -1;
}

/** Autogenrated doc for turning_right_on */
int ServiceRoverLights::turning_right_on() {

  AFB_NOTICE("[ServiceRoverLights] Turning_right_on");
  AFB_ERROR("Method Turning_right_on not implemented");

  return -1;
}
